### ISSUE TITLE
Need to register S3 print method?

### ISSUE THREAD

**Issue by rjake** [r-for-educators/flair#37]
Great work here! I'm not sure if I hit a bug or missed something in the documentation. 
I am getting the same issue from #13 where it says

```
Error in viewer(htmlFile) : could not find function "viewer"
Calls: <Anonymous> ... knit_print.default -> normal_print -> print -> print.with_flair
Execution halted
```

I'm using
```
      R  4.2.0
  flair  0.0.2
RStudio  2022.02.2#485
     OS  Windows 10
```

It seemed adding this to the Rmd fixed the issue:

````
```{r, include=FALSE}

registerS3method(
  "knit_print", "with_flair", knit_print.with_flair,
  envir = asNamespace("knitr")
)
```
````

I'm curious if this is a bug or if one of these solutions could be employed:
* add information about adding `registerS3method()` to an Rmd under `?knit_print.with_flair()`
* adding a template to the package that shows how to knit this. I tried knitting the vignette and that also threw the error

**Comment by kbodwin** [comment]
This error was related to updates in R 4.0, and it's fixed in the current dev version of `flair`. :)

Please do open another issue if you see this again after installing from GitHub!
